# Generated by Django 5.2.5 on 2025-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_add_education_kpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_kpi',
            field=models.BooleanField(default=False),
        ),
    ]
