# Generated by Django 5.2.5 on 2025-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_indicator_is_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='indicator',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
