# Generated by Django 5.2.5 on 2025-09-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_monthlyentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='target',
        ),
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.indicator')),
            ],
            options={
                'unique_together': {('indicator', 'year')},
            },
        ),
    ]
