# Generated by Django 5.2.5 on 2025-09-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_indicator_target_indicatortarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='IndicatorTarget',
        ),
    ]
