# Generated by Django 5.2.5 on 2025-09-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_indicator_current_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="current_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="indicatortarget",
            name="value",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="monthlyentry",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
