# Generated by Django 5.2.5 on 2025-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_facility_project_facilities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="indicator",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
