# Generated by Django 5.2.5 on 2025-10-03 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_active_project_is_active_indicator_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_year",
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="donors",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="core.donor"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="main_donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_projects",
                to="core.donor",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="projects_from_form",
            field=models.ManyToManyField(
                blank=True, related_name="projects_from_form", to="core.donor"
            ),
        ),
    ]
