# Generated by Django 5.2.5 on 2025-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_historicaldonor_historicalfacility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="donors", to="core.facility"
            ),
        ),
    ]
