# Generated by Django 5.2.5 on 2025-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_district_facility_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaldistrict",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalfacility",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
